"""
Django settings for smartsketch_backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env so COLAB_ML_URL is available (fallback if manage.py load_dotenv ran first)
from dotenv import load_dotenv
load_dotenv(str(BASE_DIR / ".env"))

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# Colab ML service – set in .env as COLAB_ML_URL=https://xxxx.ngrok-free.app/generate
# Django uses this URL to call the Colab Flask server for ALL heavy ML work.
COLAB_ML_URL = (os.environ.get("COLAB_ML_URL") or "").strip().rstrip("/")

# ML Engine Configuration
# ---------------------------------------------------------------
# GPU Architecture:
#   ALL heavy model inference (SDXL, Qwen, CLIP, FaceNet, ControlNet)
#   runs on the Colab notebook (GPU).  Django (Render) is CPU-only
#   and acts purely as an API gateway.
#
#   USE_LOCAL_ML must remain False on Render.
#   Set USE_LOCAL_ML=True only when running locally with a real GPU.
# ---------------------------------------------------------------
ML_CONFIG = {
    'DEVICE': os.environ.get('ML_DEVICE', 'cpu'),
    'VALIDATOR_MODEL': 'Qwen/Qwen2.5-3B-Instruct',
    'SDXL_MODEL': 'stabilityai/stable-diffusion-xl-base-1.0',
    'LORA_PATH': str(BASE_DIR / 'ml_engine' / 'weights' / 'forensic_face_v1.safetensors'),
    'LORA_STRENGTH': 0.3,
    'ENABLE_SKETCH': True,
    'ENABLE_EDITING': True,
    'ENABLE_INPAINTING': True,
    # Never load heavy models on Render; set USE_LOCAL_ML=True only with a local GPU
    'USE_LOCAL_ML': os.environ.get('USE_LOCAL_ML', 'False').lower() == 'true',
    'LOW_VRAM_MODE': os.environ.get('LOW_VRAM_MODE', 'False').lower() == 'true',
    # Remote ML URL: defaults to COLAB_ML_URL so only one env var is needed
    'REMOTE_ML_URL': (
        os.environ.get('REMOTE_ML_URL') or COLAB_ML_URL or ''
    ).strip().rstrip('/'),
}



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-swbp&3w9ir*nj@!j)0^vyftl_4(hke27ne6m*3c9s!bvr$k1-(')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

# Allow the Vercel domain and Render domain
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.onrender.com', 'smart-sketch-ai-idrj.vercel.app']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',  #frontend
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'smartsketch_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smartsketch_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# --- SQLite Performance & Concurrency Tuning ---
from django.db.backends.signals import connection_created
from django.dispatch import receiver

@receiver(connection_created)
def set_sqlite_pragma(sender, connection, **kwargs):
    if connection.vendor == 'sqlite':
        cursor = connection.cursor()
        cursor.execute('PRAGMA journal_mode=WAL;')
        cursor.execute('PRAGMA synchronous=NORMAL;')


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'api.User'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}

# JWT Settings


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}
# CORS setup
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "https://smart-sketch-ai-idrj.vercel.app",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
