# Generated by Django 6.0.4 on 2026-04-24 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editedimage',
            name='forensic_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of the pixel data', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='editedimage',
            name='is_watermarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='forensic_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of the pixel data', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='is_watermarked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AgentCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(db_index=True, max_length=255)),
                ('checkpoint_id', models.CharField(db_index=True, max_length=255)),
                ('parent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('checkpoint_data', models.BinaryField(help_text='Pickled LangGraph Checkpoint')),
                ('metadata_data', models.BinaryField(help_text='Pickled LangGraph Metadata')),
                ('version', models.IntegerField(default=1, help_text='Schema version for forward compatibility')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('thread_id', 'checkpoint_id')},
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('case_number', models.CharField(blank=True, max_length=100, null=True)),
                ('suspect_name_guess', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
