# Generated by Django 6.0.4 on 2026-04-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_editedimage_forensic_hash_editedimage_is_watermarked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentStateWrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(db_index=True, max_length=255)),
                ('checkpoint_id', models.CharField(db_index=True, max_length=255)),
                ('task_id', models.CharField(max_length=255)),
                ('idx', models.IntegerField()),
                ('channel', models.CharField(max_length=255)),
                ('value', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('thread_id', 'checkpoint_id', 'task_id', 'idx')},
            },
        ),
    ]
