import torch
import numpy as np
from PIL import Image
from gfpgan import GFPGANer

class FaceRestorer:
    """
    Enhances facial features using GFPGAN.
    Fixes blurry or distorted faces generated by SDXL.
    """
    def __init__(self, model_path: str = 'GFPGANv1.4.pth', device: str = 'cuda', upscale: int = 1):
        """
        Initialize the restorer.
        
        Args:
            model_path: Path to the GFPGAN model weight.
            device: 'cuda' or 'cpu'.
            upscale: Upscaling factor.
        """
        self.device = device
        self.upscale = upscale
        
        # Initialize GFPGANer
        # arch='clean', channel_multiplier=2 are defaults for v1.4
        self.restorer = GFPGANer(
            model_path=model_path,
            upscale=upscale,
            arch='clean',
            channel_multiplier=2,
            device=device
        )
        print(f"[FaceRestorer] Initialized GFPGAN v1.4 on {device}")

    def restore(self, image: Image.Image) -> Image.Image:
        """
        Restore/Enhance faces in the given image.
        
        Args:
            image: PIL Image to restore.
            
        Returns:
            Restored PIL Image.
        """
        # Convert PIL to CV2 format (BGR)
        img_np = np.array(image.convert('RGB'))
        img_cv2 = img_np[:, :, ::-1] # RGB to BGR
        
        # Enhance
        # _, _, restored_img = self.restorer.enhance(img_cv2, has_aligned=False, only_center_face=False, paste_back=True)
        # Note: paste_back=True ensures the enhanced face is put back into the original image context.
        _, _, restored_img = self.restorer.enhance(
            img_cv2,
            has_aligned=False,
            only_center_face=False,
            paste_back=True
        )
        
        # Convert back to PIL (RGB)
        restored_img = restored_img[:, :, ::-1] # BGR to RGB
        return Image.fromarray(restored_img)

# Helper function to download model if missing (usually handled by Modal deploy)
def download_gfpgan_model(url: str, save_path: str):
    import os
    import requests
    if not os.path.exists(save_path):
        print(f"[FaceRestorer] Downloading GFPGAN model from {url}...")
        response = requests.get(url, stream=True)
        with open(save_path, 'wb') as f:
            for chunk in response.iter_content(chunk_size=8192):
                f.write(chunk)
        print(f"[FaceRestorer] Model saved to {save_path}")
