import sys
import types

# ── Must be FIRST — inject shim before gfpgan/basicsr import chain fires ──
if 'torchvision.transforms.functional_tensor' not in sys.modules:
    import torchvision.transforms.functional as _fn
    _shim = types.ModuleType('torchvision.transforms.functional_tensor')
    _shim.__dict__.update({k: getattr(_fn, k) for k in dir(_fn) if not k.startswith('__')})
    sys.modules['torchvision.transforms.functional_tensor'] = _shim

import torch
import numpy as np
from PIL import Image


class FaceRestorer:
    """
    Enhances facial features using GFPGAN.
    Fixes blurry or distorted faces generated by SDXL.
    """
    def __init__(self, model_path: str = '/models/GFPGANv1.4.pth', device: str = 'cuda', upscale: int = 1):
        self.device = device
        self.upscale = upscale
        self.restorer = None

        try:
            from gfpgan import GFPGANer
            self.restorer = GFPGANer(
                model_path=model_path,
                upscale=upscale,
                arch='clean',
                channel_multiplier=2,
                device=device
            )
            print(f"[FaceRestorer] Initialized GFPGAN v1.4 on {device}")
        except Exception as e:
            print(f"[FaceRestorer] GFPGAN unavailable ({e}), using passthrough mode")

    def restore(self, image: Image.Image) -> Image.Image:
        if self.restorer is None:
            return image
        try:
            img_np = np.array(image.convert('RGB'))
            img_cv2 = img_np[:, :, ::-1]  # RGB to BGR
            _, _, restored_img = self.restorer.enhance(
                img_cv2,
                has_aligned=False,
                only_center_face=True,
                paste_back=True,
            )
            restored_img = restored_img[:, :, ::-1]  # BGR to RGB
            return Image.fromarray(restored_img)
        except Exception as e:
            print(f"[FaceRestorer] Restoration failed ({e}), returning original")
            return image
